package techbasics.config;

import org.springframework.boot.web.servlet.ServletRegistrationBean;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.ws.config.annotation.EnableWs;
import org.springframework.ws.config.annotation.WsConfigurerAdapter;
import org.springframework.ws.transport.http.MessageDispatcherServlet;
import org.springframework.ws.wsdl.wsdl11.DefaultWsdl11Definition;
import org.springframework.xml.xsd.SimpleXsdSchema;
import org.springframework.xml.xsd.XsdSchema;
import techbasics.api.soapservice.v1.service.SoapService;
import techbasics.aspect.SoapBoundaryLoggerAspect;

@EnableWs
@Configuration
public class WebServiceConfig extends WsConfigurerAdapter {

	@Bean
	public SoapBoundaryLoggerAspect soapBoundaryLoggerAspect() {
		return new SoapBoundaryLoggerAspect();
	}

	@Bean
	public ServletRegistrationBean messageDispatcherServlet(ApplicationContext applicationContext) {
		MessageDispatcherServlet servlet = new MessageDispatcherServlet();
		servlet.setApplicationContext(applicationContext);
		servlet.setTransformWsdlLocations(true);
		return new ServletRegistrationBean(servlet, "/soapService/*");
	}

	/////////////////////////////////////////////
	// Configuration for different endpoints base on the schemas generated by the jaxb2-maven-plugin plugin in the module pom.
	/////////////////////////////////////////////

	//SoapService V1
	//WSDL: http://localhost:8080/soapService/v1.wsdl
	@Bean(name = "v1")
	public DefaultWsdl11Definition soapServiceV1Wsdl11Definition(XsdSchema soapServiceV1Schema) {
		DefaultWsdl11Definition wsdl11Definition = new DefaultWsdl11Definition();
		wsdl11Definition.setPortTypeName("SoapServicePort");
		wsdl11Definition.setLocationUri("/soapService");
		wsdl11Definition.setTargetNamespace(SoapService.NAMESPACE_URI_V1);
		wsdl11Definition.setSchema(soapServiceV1Schema);
		return wsdl11Definition;
	}

	@Bean
	public XsdSchema soapServiceV1Schema() {
		return new SimpleXsdSchema(new ClassPathResource("schema1.xsd"));
	}


	//SoapService v2
	//WSDL: http://localhost:8080/soapService/v2.wsdl
//	@Bean(name = "v2")
//	public DefaultWsdl11Definition soapServiceV2Wsdl11Definition(XsdSchema soapServiceV2Schema) {
//		DefaultWsdl11Definition wsdl11Definition = new DefaultWsdl11Definition();
//		wsdl11Definition.setPortTypeName("SoapServicePort");
//		wsdl11Definition.setLocationUri("/soapService");
//		wsdl11Definition.setTargetNamespace(SoapService.NAMESPACE_URI_V1);
//		wsdl11Definition.setSchema(soapServiceV2Schema);
//		return wsdl11Definition;
//	}
//
//	@Bean
//	public XsdSchema soapServiceV2Schema() {
//		return new SimpleXsdSchema(new ClassPathResource("schema2.xsd"));
//	}

}
